In [1]:
import pandas as pd 
import numpy as np
import geopandas as gpd

In [2]:
noise_data1 = pd.read_csv('311_Noise_Complaints.csv')

c:\Users\20228\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (17,18,20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
noise_data = noise_data1.copy()

In [4]:
noise_data.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [5]:
noise_data['Descriptor'].unique()

array(['Loud Music/Party', 'Banging/Pounding', 'Loud Talking',
       'Car/Truck Music', 'Loud Television', 'Other', 'Engine Idling',
       'Car/Truck Horn', 'Noise, Barking Dog (NR5)',
       'Noise: air condition/ventilation equipment (NV1)',
       'Noise: Construction Before/After Hours (NM1)',
       'Noise: Alarms (NR3)', 'Noise', 'Noise: Boat(Engine',
       'Noise: Jack Hammering (NC2)',
       'Noise: Construction Equipment (NC1)',
       'Noise, Other Animals (NR6)', 'NYPD',
       'Noise: Private Carting Noise (NQ1)', '21 Collection Truck Noise',
       'News Gathering', 'Noise: Manufacturing Noise (NK1)',
       'Noise, Ice Cream Truck (NR4)',
       'Noise:  lawn care equipment (NCL)',
       'Noise: Other Noise Sources (Use Comments) (NZZ)',
       'Noise: Boat(Engine,Music,Etc) (NR10)', 'Noise: Vehicle (NR2)',
       'Noise: Loud Music/Daytime (Mark Date And Time) (NN1)',
       'Noise: Air Condition/Ventilation Equip, Residential (NJ1)', nan,
       'People Created Noise',
       'Noise: Air Condition/Ventilation Equip, Commercial (NJ2)',
       'Horn Honking Sign Requested (NR9)',
       'Construction Before/After Hours - For DEP Internal Use Only',
       'Noise: Loud Music/Nighttime(Mark Date And Time) (NP1)',
       'Flying Too Low', 'Passing By', 'Hovering',
       'Noise: Loud Music From Siebel System - For Dep Internal Use Only (NP21)'],
      dtype=object)

In [6]:
noise_data = noise_data[['Unique Key','Created Date','Closed Date','Agency','Agency Name','Descriptor','Complaint Type','Resolution Description','Resolution Action Updated Date','Incident Zip','Borough','Latitude','Longitude','Location']]

'':'',

In [7]:
noise_data = noise_data.rename(columns={'Unique Key':'Unique_Key','Created Date':'Created_Date','Closed Date':'Closed_Date','Agency Name':'Agency_Name',
'Complaint Type':'Complaint_Type','Resolution Description':'Resolution_Description','Resolution Action Updated Date':'Resolution_Action_UpdatedDate',
'Incident Zip':'zipcode',
'Location':'Location'})

In [8]:
a = list(noise_data.columns)

In [9]:
noise_data['Borough'].replace('',np.nan,inplace=True)
noise_data['Borough'].replace('Unspecified',np.nan,inplace=True)
noise_data.dropna(subset=['Borough'],inplace=True)

In [10]:
noise_data['zipcode'].replace('',np.nan,inplace=True)
noise_data['zipcode'].replace('Unspecified',np.nan,inplace=True)
noise_data.dropna(subset=['zipcode'],inplace=True)

In [11]:
for i in a:
    noise_data[i].replace('',np.nan,inplace=True)
    noise_data.dropna(subset=[i],inplace=True)

In [12]:
noise_data.drop(noise_data[noise_data['zipcode']==0].index,inplace=True)

In [13]:
noise_data['Created_Date'] = pd.to_datetime(noise_data['Created_Date'],format='%m/%d/%Y %I:%M:%S %p')

In [14]:
noise_date_19_21=noise_data[(noise_data['Created_Date'].dt.year >= 2019)&(noise_data['Created_Date'].dt.year <= 2021)]

In [15]:
noise_date_19_21.sort_values("Created_Date")

,Unique_Key,Created_Date,Closed_Date,Agency,Agency_Name,Descriptor,Complaint_Type,Resolution_Description,Resolution_Action_UpdatedDate,zipcode,Borough,Latitude,Longitude,Location
3240576,41312454,2019-01-01 00:00:29,01/01/2019 02:22:46 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2019 02:22:46 AM,11231.0,BROOKLYN,40.677201,-74.010351,"(40.677200581770165, -74.01035058400049)"
3240284,41310350,2019-01-01 00:00:43,01/01/2019 02:21:44 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2019 02:21:44 AM,11365.0,QUEENS,40.738062,-73.781277,"(40.738061586139345, -73.78127702459108)"
3239839,41307350,2019-01-01 00:02:13,01/02/2019 02:07:11 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Commercial,The Police Department responded to the complai...,01/02/2019 02:07:11 AM,10003.0,MANHATTAN,40.732710,-73.987617,"(40.73271049805848, -73.9876165807211)"
3240752,41313215,2019-01-01 00:03:08,01/01/2019 07:01:51 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2019 07:01:51 AM,11417.0,QUEENS,40.684311,-73.835678,"(40.68431070731603, -73.83567813039491)"
3240812,41314022,2019-01-01 00:04:42,01/01/2019 02:22:46 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2019 02:22:47 AM,11220.0,BROOKLYN,40.644585,-74.003679,"(40.64458477457925, -74.00367912936666)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5142132,52938597,2021-12-31 23:59:11,01/01/2022 04:38:53 AM,NYPD,New York City Police Department,Loud Talking,Noise - Residential,The Police Department responded to the complai...,01/01/2022 04:39:00 AM,11377.0,QUEENS,40.741435,-73.891155,"(40.741434703903906, -73.89115451761582)"
1688,52935775,2021-12-31 23:59:23,01/01/2022 12:40:53 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2022 12:40:58 AM,11233.0,BROOKLYN,40.676669,-73.906078,"(40.676668652867846, -73.90607756368304)"
1099,52933169,2021-12-31 23:59:36,01/01/2022 01:17:56 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2022 01:18:06 AM,10462.0,BRONX,40.856004,-73.866657,"(40.85600417771388, -73.86665672306978)"
4906144,52934081,2021-12-31 23:59:38,01/01/2022 01:04:48 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2022 01:04:51 AM,10001.0,MANHATTAN,40.749342,-74.002963,"(40.74934157313015, -74.0029630901275)"
1632,52935690,2021-12-31 23:59:43,01/01/2022 12:42:07 AM,NYPD,New York City Police Department,Loud Music/Party,Noise - Residential,The Police Department responded to the complai...,01/01/2022 12:42:13 AM,11417.0,QUEENS,40.678764,-73.861304,"(40.67876431813203, -73.86130391198398)"

In [16]:
len(noise_date_19_21)

1980523

In [17]:
noise_date_19_21 = noise_date_19_21.loc[(noise_date_19_21["Resolution_Description"] !=  'The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.') & (noise_date_19_21["Resolution_Description"] !=  'The Police Department responded to the complaint and determined that police action was not necessary.')]

In [18]:
noise_date_19_21[noise_date_19_21["Resolution_Description"]=='The Police Department responded to the complaint and determined that police action was not necessary.']

Empty DataFrame
Columns: [Unique_Key, Created_Date, Closed_Date, Agency, Agency_Name, Descriptor, Complaint_Type, Resolution_Description, Resolution_Action_UpdatedDate, zipcode, Borough, Latitude, Longitude, Location]
Index: []

In [19]:
noise_date_19_21.to_json('noise_date.json')

In [ ]:
noise_date_19_21.to_csv('noise_data.csv')

In [16]:
import json

In [17]:
with open('noise_date.json') as f:
    data = json.load(f)

In [18]:
noise_data.shape

(5151236, 6)

# 读取一下shapefile文件

In [19]:
gdf = gpd.read_file("ZIP_CODE_040114/ZIP_CODE_040114.shp")
gdf.sort_values('ZIPCODE',inplace=True, ascending=True)
gdf

,ZIPCODE,BLDGZIP,PO_NAME,POPULATION,AREA,STATE,COUNTY,ST_FIPS,CTY_FIPS,URL,SHAPE_AREA,SHAPE_LEN,geometry
54,00083,0,Central Park,25.0,3.830099e+07,NY,New York,36,061,http://www.usps.com/,0.0,0.0,"POLYGON ((998309.725 229616.681, 998282.853 22..."
82,10001,0,New York,22413.0,1.779494e+07,NY,New York,36,061,http://www.usps.com/,0.0,0.0,"POLYGON ((981958.647 213464.453, 981980.328 21..."
92,10002,0,New York,81305.0,2.628013e+07,NY,New York,36,061,http://www.usps.com/,0.0,0.0,"POLYGON ((991339.870 207576.784, 991330.490 20..."
90,10003,0,New York,55878.0,1.553838e+07,NY,New York,36,061,http://www.usps.com/,0.0,0.0,"POLYGON ((989830.469 207048.126, 989716.354 20..."
113,10004,0,New York,2187.0,7.679616e+06,NY,New York,36,061,http://www.usps.com/,0.0,0.0,"POLYGON ((977542.450 188447.278, 977523.000 18..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,11693,0,Far Rockaway,11052.0,1.227092e+07,NY,Queens,36,081,http://www.usps.com/,0.0,0.0,"POLYGON ((1036087.150 154632.639, 1036096.661 ..."
259,11693,0,Far Rockaway,11052.0,3.497516e+06,NY,Kings,36,047,http://www.usps.com/,0.0,0.0,"POLYGON ((1028453.995 167153.410, 1027813.010 ..."
134,11693,0,Far Rockaway,11052.0,4.647173e+07,NY,Queens,36,081,http://www.usps.com/,0.0,0.0,"POLYGON ((1030865.641 170727.666, 1030861.340 ..."
151,11694,0,Rockaway Park,20163.0,4.810161e+07,NY,Queens,36,081,http://www.usps.com/,0.0,0.0,"POLYGON ((1034425.420 153503.826, 1034416.180 ..."
154,11697,0,Breezy Point,4079.0,5.978976e+07,NY,Queens,36,081,http://www.usps.com/,0.0,0.0,"POLYGON ((1016691.780 146366.409, 1016655.757 ..."

In [20]:
gdf.drop(['POPULATION','SHAPE_AREA','SHAPE_LEN','STATE','AREA'],axis=1,inplace=True)

In [21]:
complaints_by_zip = noise_date_19_21['zipcode'].value_counts().to_frame('nc_freq')
complaints_by_zip = pd.DataFrame(complaints_by_zip).reset_index()
complaints_by_zip.columns = ['ZIPCODE', 'count']
complaints_by_zip['ZIPCODE'] = pd.to_numeric(complaints_by_zip['ZIPCODE'])
complaints_by_zip.sort_values('ZIPCODE',inplace=True, ascending=True)
complaints_by_zip.head()

     ZIPCODE  count
210     83.0      5
174  10000.0    356
63   10001.0  11385
18   10002.0  24513
40   10003.0  16809

In [22]:
noise_false = noise_date_19_21.loc[(noise_date_19_21["Resolution_Description"] ==  'The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.') | (noise_date_19_21["Resolution_Description"] ==  'The Police Department responded to the complaint and determined that police action was not necessary.')]

In [23]:
false_complaints_by_zip = noise_false['zipcode'].value_counts().to_frame('nc_freq')
false_complaints_by_zip = pd.DataFrame(false_complaints_by_zip).reset_index()
false_complaints_by_zip.columns = ['ZIPCODE', 'count']
false_complaints_by_zip['ZIPCODE'] = pd.to_numeric(false_complaints_by_zip['ZIPCODE'])
false_complaints_by_zip.sort_values(by=['ZIPCODE'],inplace=True, ascending=True)
false_complaints_by_zip.head()

     ZIPCODE  count
217     83.0      1
176  10000.0    111
68   10001.0   4682
30   10002.0  10005
42   10003.0   7137

In [ ]:
false_complaints_by_zip['ZIPCODE'] = false_complaints_by_zip['ZIPCODE'].apply(int)

## False Complaints by Zipcode 错误的报告 查看

In [25]:
cmplts = pd.merge(complaints_by_zip, false_complaints_by_zip, on='ZIPCODE')
cmplts

     ZIPCODE  count_x  count_y
0       83.0        5        1
1    10000.0      356      111
2    10001.0    11385     4682
3    10002.0    24513    10005
4    10003.0    16809     7137
..       ...      ...      ...
213  11692.0     2748     1428
214  11693.0     2600     1190
215  11694.0     2873     1205
216  11697.0      147       63
217  12345.0       64       27

[218 rows x 3 columns]

In [26]:
cmplts['ZIPCODE'] = cmplts['ZIPCODE'].apply(int)

In [27]:
cmplts["True"] = cmplts["count_x"].subtract(cmplts["count_y"], fill_value=0)
cmplts = cmplts.rename(columns={"count_x": "All", "count_y":"False"})
cmplts["True Percent"] = 100*(cmplts["True"]/cmplts["All"])
cmplts["False Percent"] = 100*(cmplts["False"]/cmplts["All"])
cmplts.head()

   ZIPCODE    All  False   True  True Percent  False Percent
0       83      5      1      4     80.000000      20.000000
1    10000    356    111    245     68.820225      31.179775
2    10001  11385   4682   6703     58.875714      41.124286
3    10002  24513  10005  14508     59.184922      40.815078
4    10003  16809   7137   9672     57.540603      42.459397

In [28]:
cmplts

     ZIPCODE    All  False   True  True Percent  False Percent
0         83      5      1      4     80.000000      20.000000
1      10000    356    111    245     68.820225      31.179775
2      10001  11385   4682   6703     58.875714      41.124286
3      10002  24513  10005  14508     59.184922      40.815078
4      10003  16809   7137   9672     57.540603      42.459397
..       ...    ...    ...    ...           ...            ...
213    11692   2748   1428   1320     48.034934      51.965066
214    11693   2600   1190   1410     54.230769      45.769231
215    11694   2873   1205   1668     58.057779      41.942221
216    11697    147     63     84     57.142857      42.857143
217    12345     64     27     37     57.812500      42.187500

[218 rows x 6 columns]

In [29]:
cmplts['ZIPCODE'].unique()

array([   83, 10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007,
       10009, 10010, 10011, 10012, 10013, 10014, 10016, 10017, 10018,
       10019, 10020, 10021, 10022, 10023, 10024, 10025, 10026, 10027,
       10028, 10029, 10030, 10031, 10032, 10033, 10034, 10035, 10036,
       10037, 10038, 10039, 10040, 10041, 10044, 10045, 10065, 10069,
       10075, 10103, 10105, 10106, 10111, 10112, 10115, 10118, 10119,
       10120, 10121, 10122, 10123, 10128, 10152, 10153, 10154, 10158,
       10162, 10165, 10167, 10169, 10170, 10172, 10174, 10178, 10278,
       10280, 10281, 10282, 10301, 10302, 10303, 10304, 10305, 10306,
       10307, 10308, 10309, 10310, 10312, 10314, 10451, 10452, 10453,
       10454, 10455, 10456, 10457, 10458, 10459, 10460, 10461, 10462,
       10463, 10464, 10465, 10466, 10467, 10468, 10469, 10470, 10471,
       10472, 10473, 10474, 10475, 11001, 11004, 11005, 11040, 11101,
       11102, 11103, 11104, 11105, 11106, 11109, 11201, 11203, 11204,
       11205, 11206, 11207, 11208, 11209, 11210, 11211, 11212, 11213,
       11214, 11215, 11216, 11217, 11218, 11219, 11220, 11221, 11222,
       11223, 11224, 11225, 11226, 11228, 11229, 11230, 11231, 11232,
       11233, 11234, 11235, 11236, 11237, 11238, 11239, 11241, 11249,
       11251, 11354, 11355, 11356, 11357, 11358, 11359, 11360, 11361,
       11362, 11363, 11364, 11365, 11366, 11367, 11368, 11369, 11370,
       11371, 11372, 11373, 11374, 11375, 11377, 11378, 11379, 11385,
       11411, 11412, 11413, 11414, 11415, 11416, 11417, 11418, 11419,
       11420, 11421, 11422, 11423, 11426, 11427, 11428, 11429, 11430,
       11432, 11433, 11434, 11435, 11436, 11691, 11692, 11693, 11694,
       11697, 12345], dtype=int64)

# 可视化数据

In [30]:
round(cmplts['ZIPCODE'],0)

0         83
1      10000
2      10001
3      10002
4      10003
       ...
213    11692
214    11693
215    11694
216    11697
217    12345
Name: ZIPCODE, Length: 218, dtype: int64

In [31]:
cmplts['ZIPCODE'] = cmplts['ZIPCODE'].apply(int)

In [32]:
gdf['ZIPCODE'] = gdf['ZIPCODE'].apply(int)

In [33]:
cmplts.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 218 entries, 0 to 217
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ZIPCODE        218 non-null    int64
 1   All            218 non-null    int64
 2   False          218 non-null    int64
 3   True           218 non-null    int64
 4   True Percent   218 non-null    float64
 5   False Percent  218 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 11.9 KB

In [34]:
gdf = pd.merge(gdf,cmplts, on ='ZIPCODE')
gdf

,ZIPCODE,BLDGZIP,PO_NAME,COUNTY,ST_FIPS,CTY_FIPS,URL,geometry,All,False,True,True Percent,False Percent
0,83,0,Central Park,New York,36,061,http://www.usps.com/,"POLYGON ((998309.725 229616.681, 998282.853 22...",5,1,4,80.000000,20.000000
1,10001,0,New York,New York,36,061,http://www.usps.com/,"POLYGON ((981958.647 213464.453, 981980.328 21...",11385,4682,6703,58.875714,41.124286
2,10002,0,New York,New York,36,061,http://www.usps.com/,"POLYGON ((991339.870 207576.784, 991330.490 20...",24513,10005,14508,59.184922,40.815078
3,10003,0,New York,New York,36,061,http://www.usps.com/,"POLYGON ((989830.469 207048.126, 989716.354 20...",16809,7137,9672,57.540603,42.459397
4,10004,0,New York,New York,36,061,http://www.usps.com/,"POLYGON ((977542.450 188447.278, 977523.000 18...",1033,328,705,68.247822,31.752178
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,11693,0,Far Rockaway,Queens,36,081,http://www.usps.com/,"POLYGON ((1036087.150 154632.639, 1036096.661 ...",2600,1190,1410,54.230769,45.769231
223,11693,0,Far Rockaway,Kings,36,047,http://www.usps.com/,"POLYGON ((1028453.995 167153.410, 1027813.010 ...",2600,1190,1410,54.230769,45.769231
224,11693,0,Far Rockaway,Queens,36,081,http://www.usps.com/,"POLYGON ((1030865.641 170727.666, 1030861.340 ...",2600,1190,1410,54.230769,45.769231
225,11694,0,Rockaway Park,Queens,36,081,http://www.usps.com/,"POLYGON ((1034425.420 153503.826, 1034416.180 ...",2873,1205,1668,58.057779,41.942221
226,11697,0,Breezy Point,Queens,36,081,http://www.usps.com/,"POLYGON ((1016691.780 146366.409, 1016655.757 ...",147,63,84,57.142857,42.857143

In [35]:
gdf.iloc[35]

ZIPCODE                                                      10034
BLDGZIP                                                          0
PO_NAME                                                   New York
COUNTY                                                    New York
ST_FIPS                                                         36
CTY_FIPS                                                       061
URL                                           http://www.usps.com/
geometry         POLYGON ((1006203.169008225 257345.6566181332,...
All                                                          38666
False                                                        19973
True                                                         18693
True Percent                                               48.3448
False Percent                                              51.6552
Name: 35, dtype: object

In [36]:
len(gdf)

227

In [37]:
gdf["center"] = gdf["geometry"].centroid
gdf_points = gdf.copy()
gdf_points.set_geometry("center", inplace = True)

In [38]:
gdf["center"]

0       POINT (993788.745 224355.692)
1       POINT (985100.719 212599.489)
2       POINT (988220.438 200190.136)
3       POINT (987340.306 205944.672)
4       POINT (978956.290 190228.148)
                    ...
222    POINT (1036583.432 153268.986)
223    POINT (1028655.626 168862.387)
224    POINT (1032833.368 164480.173)
225    POINT (1025428.478 148865.652)
226    POINT (1008236.666 142374.238)
Name: center, Length: 227, dtype: geometry

In [39]:
gdf.columns

Index(['ZIPCODE', 'BLDGZIP', 'PO_NAME', 'COUNTY', 'ST_FIPS', 'CTY_FIPS', 'URL',
       'geometry', 'All', 'False', 'True', 'True Percent', 'False Percent',
       'center'],
      dtype='object')

In [40]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 227 entries, 0 to 226
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ZIPCODE        227 non-null    int64
 1   BLDGZIP        227 non-null    object
 2   PO_NAME        227 non-null    object
 3   COUNTY         227 non-null    object
 4   ST_FIPS        227 non-null    object
 5   CTY_FIPS       227 non-null    object
 6   URL            227 non-null    object
 7   geometry       227 non-null    geometry
 8   All            227 non-null    int64
 9   False          227 non-null    int64
 10  True           227 non-null    int64
 11  True Percent   227 non-null    float64
 12  False Percent  227 non-null    float64
 13  center         227 non-null    geometry
dtypes: float64(2), geometry(2), int64(4), object(6)
memory usage: 26.6+ KB

In [41]:

gdf['False'] = gdf['False'].apply(float)
gdf['All'] = gdf['All'].apply(float)
gdf['True'] = gdf['All']-gdf['False']

In [42]:
len(gdf)

227

In [46]:
gdf.to_excel('gd65.xlsx')

In [44]:
pd.read_csv('gdf5.csv')

,Unnamed: 0,ZIPCODE,BLDGZIP,PO_NAME,POPULATION,AREA,STATE,COUNTY,ST_FIPS,CTY_FIPS,URL,SHAPE_AREA,SHAPE_LEN,geometry,All,False,True,True Percent,False Percent,center
0,0,83,0,Central Park,25.0,3.830099e+07,NY,New York,36,61,http://www.usps.com/,0.0,0.0,"POLYGON ((998309.7254775614 229616.6812362969,...",5.0,1.0,4.0,80.000000,20.000000,POINT (993788.7445239611 224355.691894618)
1,1,10001,0,New York,22413.0,1.779494e+07,NY,New York,36,61,http://www.usps.com/,0.0,0.0,"POLYGON ((981958.6472873986 213464.4530421346,...",11385.0,4682.0,6703.0,58.875714,41.124286,POINT (985100.7190546701 212599.4890663367)
2,2,10002,0,New York,81305.0,2.628013e+07,NY,New York,36,61,http://www.usps.com/,0.0,0.0,"POLYGON ((991339.8703228086 207576.7837151289,...",24513.0,10005.0,14508.0,59.184922,40.815078,POINT (988220.4376830176 200190.1363864965)
3,3,10003,0,New York,55878.0,1.553838e+07,NY,New York,36,61,http://www.usps.com/,0.0,0.0,"POLYGON ((989830.469142139 207048.1263078749, ...",16809.0,7137.0,9672.0,57.540603,42.459397,POINT (987340.3063401638 205944.6723427543)
4,4,10004,0,New York,2187.0,7.679616e+06,NY,New York,36,61,http://www.usps.com/,0.0,0.0,"POLYGON ((977542.4500830621 188447.2783390433,...",1033.0,328.0,705.0,68.247822,31.752178,POINT (978956.2904805684 190228.1479848956)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,222,11693,0,Far Rockaway,11052.0,1.227092e+07,NY,Queens,36,81,http://www.usps.com/,0.0,0.0,"POLYGON ((1036087.150250643 154632.6386193782,...",2600.0,1190.0,1410.0,54.230769,45.769231,POINT (1036583.431720455 153268.9857368148)
223,223,11693,0,Far Rockaway,11052.0,3.497516e+06,NY,Kings,36,47,http://www.usps.com/,0.0,0.0,"POLYGON ((1028453.99491331 167153.4098376334, ...",2600.0,1190.0,1410.0,54.230769,45.769231,POINT (1028655.62635488 168862.3869956877)
224,224,11693,0,Far Rockaway,11052.0,4.647173e+07,NY,Queens,36,81,http://www.usps.com/,0.0,0.0,"POLYGON ((1030865.641008645 170727.6658124626,...",2600.0,1190.0,1410.0,54.230769,45.769231,POINT (1032833.368058156 164480.1734438057)
225,225,11694,0,Rockaway Park,20163.0,4.810161e+07,NY,Queens,36,81,http://www.usps.com/,0.0,0.0,"POLYGON ((1034425.419650227 153503.8255883008,...",2873.0,1205.0,1668.0,58.057779,41.942221,POINT (1025428.477834981 148865.6516664001)
226,226,11697,0,Breezy Point,4079.0,5.978976e+07,NY,Queens,36,81,http://www.usps.com/,0.0,0.0,"POLYGON ((1016691.779920727 146366.408760801, ...",147.0,63.0,84.0,57.142857,42.857143,POINT (1008236.665721081 142374.2376868589)

In [45]:
result = []
for i in range(0,len(gdf)):
    r = gdf.iloc[i]
    result.append({'ZIPCODE':r['ZIPCODE'],'BLDGZIP':r['BLDGZIP'],'PO_NAME':r['PO_NAME'],'POPULATION':r['POPULATION'],'AREA':r['AREA'],'STATE':r['STATE'],
    'COUNTY':r['COUNTY'],'ST_FIPS':r['ST_FIPS'],'CTY_FIPS':r['CTY_FIPS'],'URL':r['URL']
    ,'All':r['All'],'False':r['False'],'True':r['True'],'True_Percent':r['True Percent'],'False_Percent':r['False Percent']})

KeyError: 'POPULATION'

In [ ]:
import json
f = open('data1.geojson',mode='w')
json.dump(result,f)
f.close()